# Generated by Django 4.1.1 on 2023-02-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_category_item_img_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_api.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default=1, upload_to='product/'),
            preserve_default=False,
        ),
    ]
